### ISSUE TITLE
Bottleneck of Py1 code is that it relies on gunzip to feed stdin 

### ISSUE THREAD

**Issue by taoliu** [lh3/kmer-cnt#2]
The current `kc-py1 + Python3.7` implementation spends 10 folds longer time than `kc-c2` or `kc-c3`.  However, it may only due to the fact that `kc-py1` reads stdin and it may rely on command line `gunzip -c` to feed. Python has built-in gzip library, and if I use `python-gzip` to read the testing file `M_abscessus_HiSeq_10M.fa.gz`, the whole process will be 10x faster. See [kc-py2.py](/taoliu/kmer-cnt/blob/feat-cython/kc-py2.py). Here is the test. I used my `prockreport` script to track the CPU time and Max memory usage (it calls `ps` in 0.5s interval).
 
```
$ wget https://gist.githubusercontent.com/taoliu/2501892/raw/92a66ba0cf6026dbdc0d3f941a9f8d6be6d6c176/prockreport
$ wget https://github.com/lh3/kmer-cnt/releases/download/v0.1/M_abscessus_HiSeq_10M.fa.gz
$ gunzip -c M_abscessus_HiSeq_10M.fa.gz | python kc-py1.py &> py1.out &
$ bash prockreport 0.5 $!
CPU time (mm:ss): 00:04:01
Max mem (KB): 8551588
$ python kc-py2.py 31  M_abscessus_HiSeq_10M.fa.gz &> py2.out &
$ bash prockreport 0.5 $!
CPU time (mm:ss): 00:00:40
Max mem (KB): 3468044
$ kc-c2 M_abscessus_HiSeq_10M.fa.gz &>c2.out &
$ bash prockreport 0.5 $!
CPU time (mm:ss): 00:00:29
Max mem (KB): 1107240
$ kc-c3 M_abscessus_HiSeq_10M.fa.gz &>c3.out &
$ bash prockreport 0.5 $!
CPU time (mm:ss): 00:00:30
Max mem (KB): 1217792
```

The observation is that the `kc-py1.py+gunzip`  took 4mins (240s) and 8G memory, however `kc-py2` on gzip file directly took only 40s and 3.5G memory.  On the same server, `kc-c2` or `kc-c3` took 30s and 1.1-1.2G mem.  So in fact, the difference is not that ginormous. I modified `kc-py2` in Cython (not submitted to github yet) by specifying types of all variables and it can make the simple python counter to finish in 34s although the memory usage is still 3 times larger than `kc-c2` or `kc-c3`.

The testing environment is a desktop server with Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz, 64G mem and SSD.

**Comment by lh3** [comment]
But the kc-py2.py results are wrong.

**Comment by taoliu** [comment]
@lh3 Oh, my bad! There is an indent issue... I changed tabs in your code to 4 spaces and that caused a problem in a for loop. In my previous experience, python-gzip is slower than the gzip tool. Now it turns out to be quite slow now. Issue closed :)

**Comment by lh3** [comment]
Thanks for investigating this. I just hate this SPACE vs TAB thing. It has bitten me a few times...
